name: homis ChatOps

on:
  repository_dispatch:
    types: [chat_ops]
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn ts-node ./src/tasks/${{ github.event.client_payload.task }}/task.ts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PAYLOAD: "${{ toJSON(github.event.client_payload) }}"
